/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormulaNameRouteImport } from './routes/formula.$name'

const FormulaNameRoute = FormulaNameRouteImport.update({
  id: '/formula/$name',
  path: '/formula/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/formula/$name': typeof FormulaNameRoute
}
export interface FileRoutesByTo {
  '/formula/$name': typeof FormulaNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/formula/$name': typeof FormulaNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/formula/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/formula/$name'
  id: '__root__' | '/formula/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormulaNameRoute: typeof FormulaNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formula/$name': {
      id: '/formula/$name'
      path: '/formula/$name'
      fullPath: '/formula/$name'
      preLoaderRoute: typeof FormulaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FormulaNameRoute: FormulaNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
